<?php

/**
 * @file
 * Contains lv_interface.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function lv_interface_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lv_interface module.
    case 'help.page.lv_interface':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Interface between frontend and drupal.') . '</p>';
      return $output;

    default:
  }
}
